### PR TITLE
Add Truffleruby head to CI

### PR DESCRIPTION
**Pull request by gogainda**

### CODE REVIEW

**Comment by simi** [comment]
:wave: @gogainda, can you elaborate a little why is this needed? I think it is not good idea to add `head` version to general CI since it can broke the build at any time.

But if you would like to test on `head` version anyway, I'm ok with weekly build for `head` (you can include `ruby-head` as well).

https://docs.github.com/en/actions/reference/events-that-trigger-workflows#schedule

**Comment by gogainda** [comment]
From stability point of view truffleruby-head should be the same as truffleruby, but looks like stable version works as well, so I changed to to regular `truffleruby`

**Comment by simi** [comment]
It is the same actually, we need to pin version. For example `truffleruby-21.0.0`. But what's the purpose of this? Is is having rapid development and it is not really stable AFAIK. Do you use `truffleruby` in production with `omniauth-facebook`?

**Comment by gogainda** [comment]
We are exploring  how many gems are currently supporting truffleruby (quite may already). To do this I check every popular gem and add info about it to the  https://github.com/eregon/truffleruby-gem-tracker project. It should help us with:
1. Track how many gems are currently supported
2. React faster on any regressions for those gems

**Comment by simi** [comment]
Than indeed I think it would make more sense to make this scheduled check, since there is not much activity on this gem (except when moving to new FB API by default).

**Pull request closed without merging**
