### PR TITLE
addds ruby 3 to CI matrix

### PR DESCRIPTION
**Pull request by swiknaba**
adds Ruby 3 to CI. Also gitignored a ruby-version file so I can run the tests locally for different versions.

I've run the tests locally for Ruby 3, all ✅ 

closes https://github.com/simi/omniauth-facebook/issues/351

### CODE REVIEW

**Comment by simi** [comment]
Thanks @swiknaba!

I don't really understand the `.ruby-version` ignoring. Can you please remove it? Also it seems to fail thanks to rbx platform specific gems. Can you remove that from `Gemfile` as well? We don't test `rbx` anymore.

**Comment by swiknaba** [comment]
I've set Ruby 2.7 and 3 in the ruby version locally, to install and run the tests on different versions. Aha, de failure is not related to the cache. I can roll that change in CI back if you want.

I can remove the ruby-version and the rbx.

**Comment by simi** [comment]
I think we can revert to using ruby/setup-ruby bundler cache and we're ready to go!

**Comment by simi** [comment]
@swiknaba thanks! :tada:

**Pull request merged**
