### PR TITLE
Upgrade Facebook Graph API to 3.0 (major gem version upgrade)

### PR DESCRIPTION
**Pull request by springerigor**
**Version 3.0**
Released May 1, 2018 | Available until July 26, 2020

https://developers.facebook.com/docs/graph-api/changelog/version3.0

### CODE REVIEW

**Comment by rtymchyk** [comment]
Is this just waiting on review?

**Comment by simi** [comment]
seems ok

**Comment by simi** [comment]
thanks for this, I'll release new gem version later today

**Comment by huoxito** [comment]
hey thanks you all for this! @simi do you think you're going to release a new version soon?

looks like v2.11 EOL is next Thursday. We recently got an email from fb complaining about our login flow and we're wondering if that's related to the version we're using (v2.11). We reached out to fb support as well and will try out latest master here if that helps resolving the issue.

**Comment by simi** [comment]
@huoxito thanks for reminder, I'll release and ping you back.

**Comment by simi** [comment]
🎉 https://rubygems.org/gems/omniauth-facebook/versions/6.0.0

**Comment by springerigor** [comment]
Thanks @simi 🙂

**Pull request merged**
